### ISSUE TITLE
[fr] implement Observable.pipe

### ISSUE THREAD

**Issue by lukepighetti** [renggli/dart-rx#4]
Would be nice to have Observable.pipe instead of having to call .lift every time

**Comment by renggli** [comment]
Agreed, but I haven't found a way that wouldn't break the benefits of the Dart type system ...

**Comment by lukepighetti** [comment]
Interesting. I'll roll that around my head and if I come up with anything I'll let you know.

**Comment by lukepighetti** [comment]
Yeah I think it can only be done if you're willing to give up on type safety.

**Comment by renggli** [comment]
One possibility without sacrificing the type system is to add methods like following to `Observable<T>` for _all_ `n`:

```dart
  Observable<T5> pipe5<T1, T2, T3, T4, T5>(
          Operator< T, T1> operator1,
          Operator<T1, T2> operator2,
          Operator<T2, T3> operator3,
          Operator<T3, T4> operator4,
          Operator<T4, T5> operator5) =>
      lift(operator1)
          .lift(operator2)
          .lift(operator3)
          .lift(operator4)
          .lift(operator5);
```

Not sure this would be useful?

**Comment by lukepighetti** [comment]
PR created to address this issue

**Comment by lukepighetti** [comment]
addressed in https://github.com/renggli/dart-rx/commit/60767a3ad07450605b4de2711c1bbbcc063896ed

**Comment by renggli** [comment]
What I noticed playing around with 60767a3 is that Dart is unable to infer the immediate types when not specified manually. For example, in this following example everything after the first filter is typed as `dynamic`:

```dart
rx.fromIterable(IntegerRange(0, 100)).pipe3(
    ops.filter((value) => value.isEven),
    ops.map((value) => '{value * value}'),
    ops.filter((value) => value.length < 3),
);
```

**Comment by lukepighetti** [comment]
I noticed that as well, it seems to be a limitation of the type system. TypeScript is much better at figuring out intermediate types.

**Comment by lukepighetti** [comment]
This should be resolved in https://github.com/renggli/dart-rx/pull/8

**Comment by lukepighetti** [comment]
resolved in https://github.com/renggli/dart-rx/commit/b955cbea7cc2009ebddb70e0d3813a041181860b

**Comment by renggli** [comment]
Unfortunately, I still can't observe correct type resolution with the example given in https://github.com/renggli/dart-rx/issues/4#issuecomment-513495277. I can only see the correct types inside the first lambda, but all types afterwards and in the result are still inferred as `dynamic`.

**Comment by lukepighetti** [comment]
Okay I see, you have to specify the types in the method, but you don't have to specify the types on every single step.

```dart
input.pipe9<String, String, String, String, String, String,
          String, String, String>(
        map((v) => '1'),
        map((v) => '2'),
        map((v) => '3'),
        map((v) => '4'),
        map((v) => '5'),
        map((v) => '6'),
        map((v) => '7'),
        map((v) => '8'),
        map((v) => '9'),
      );
```

as opposed to
```
input.pipe9<String, String, String, String, String, String,
          String, String, String>(
        map<String, String>((v) => '1'),
        map<String, String>((v) => '2'),
        map<String, String>((v) => '3'),
        map<String, String>((v) => '4'),
        map<String, String>((v) => '5'),
        map<String, String>((v) => '6'),
        map((v) => '7'),
        map<String, String>((v) => '8'),
        map<String, String>((v) => '9'),
      );
```

And this does not work
```dart
input.pipe9(
        map((v) => '1'),
        map((v) => '2'),
        map((v) => '3'),
        map((v) => '4'),
        map((v) => '5'),
        map((v) => '6'),
        map((v) => '7'),
        map((v) => '8'),
        map((v) => '9'),
      );

```

**Comment by renggli** [comment]
With static extension methods in the latest dart dev version this problem goes away: https://github.com/renggli/dart-rx/tree/extension-methods. Though no solution for the constructor methods yet.
